### ISSUE TITLE
Updating opendatatoronto on CRAN

### ISSUE THREAD

**Issue by sharlagelfand** [chircollab/chircollab20#30]
Totally copying from the drake demo last year - I need to update [opendatatoronto](https://github.com/sharlagelfand/opendatatoronto) on CRAN and am happy to demo it or show people what it looks like to remember all the steps to take :)

**Comment by emilyriederer** [comment]
Thanks for the offer, Sharla! I loved Will's demo last year, so I'm thrilled someone else is taking up the charge on this!

**Comment by sharlagelfand** [comment]
I had some checks failing on CRAN so had to update on there and don't have it to demo now, apologies!
